import type { Metadata } from "next";




export const metadata: Metadata = {
  title: "Eden conact ",
  description: "Generated by create next app",
};

export default function ContactLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
{children}
    </section>
        
      
  );
}