import type { Metadata } from "next";




export const metadata: Metadata = {
  title: "Eden Shop ",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
    {children}
        </section>
  );
}